trigger:
- main

pool:
  name: Default

steps:
- script: flutter pub get
  displayName: 'Pub Get'

- script: |
    flutter test --machine > test-results.json
    flutter pub run junitreport:tojunit --input test-results.json --output test-results.xml
  displayName: 'Ejecutar Tests'
  continueOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'test-results.xml'
    searchFolder: '$(Build.SourcesDirectory)'
    mergeTestResults: true
    testRunTitle: 'Flutter Tests'
  condition: succeededOrFailed()

- script: flutter build apk --release
  displayName: 'Build APK Release'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build/app/outputs/flutter-apk/app-release.apk'
    ArtifactName: 'apk-release'
    publishLocation: 'Container'