resources:
  repositories:
    - repository: self
      type: github
      endpoint: MiConexionGitHub
      name: tu-usuario/tu-repo-flutter

trigger:
- main

pool:
  name: Default

steps:
- script: flutter pub get
  displayName: 'Pub Get'

- script: flutter build apk --release
  displayName: 'Build APK'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build/app/outputs/flutter-apk/release/app-release.apk'
    ArtifactName: 'apk-release'
    publishLocation: 'Container'